# Generated by Django 2.1.5 on 2019-04-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='search_settings',
            field=models.IntegerField(choices=[(1, 'OR Search results'), (2, 'AND Search results')]),
        ),
    ]
