# Generated by Django 2.1.5 on 2019-03-06 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20190215_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_vote', models.IntegerField(default=0)),
                ('down_vote', models.IntegerField(default=0)),
                ('post_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='news.NewsPost')),
                ('user_id', models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
