# Generated by Django 2.1.5 on 2019-03-29 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_postvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='simulated_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postvotes',
            name='user_id',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
