# Generated by Django 2.1.5 on 2019-03-30 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190330_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvotes',
            name='user_id',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postvotes',
            name='vote_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
